<div class="">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-account">Product Image</h4>
			<div class="tools"></div>
			</div>
		<div class="fieldset">
			<div>You must take a photograph of the package before shipping.</div>
			<table>
				<tr>
					<td align="center">
						<video id="video" height="480" width="640" autoplay=""></video>
						<br/>
						<button id="snap" class="">Snap Photo</button>
					</td>
					<td align="center">
						<canvas id="canvas" height="480" width="640"></canvas>
						<br/>
						<button id="savePhoto" class="">Save Photo</button>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>